main: com.eggsnham.Main
website: https://eggsnham.com/plugins/ExplosiveArrow
author: eggsnham07
version: 0.1
name: ExplosiveArrowPlugin
api-version: 1.17
commands:
  create:
    usage: /<command> [type] [amount] 
    aliases: [crt, make, build]
    permission: eap.create

permissions:
  eap.create:
    description: Create plugin special items
    default: op
  