main: com.eggsnham.Main
website: https://eggsnham.com/plugins/ExplosiveArrow
author: eggsnham07
version: 0.4
name: ExplosiveArrowPlugin
api-version: 1.19
commands:
  create:
    description: Use this command to create plugin special items
    usage: /<command> [type] [amount] 
    aliases: [crt, make, build]